import React from "react";
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from "./Components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopping-website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     
        {children}
        <Footer />

        </body>
    </html>
  )
}
